<?php

	set_time_limit(0);

	include "commons.php";

//error_reporting(E_ALL);
//ini_set('display_errors', 1);

	function saveImage($name, $u) {
		file_put_contents($name, file_get_contents($u));
	}

	if(!isset($_GET["token"]))
		die("Unauthorized.");
	else
		$token = $_GET["token"];
	
	$offset = 0;
	$asd = array();

	echo "<!DOCTYPE html>\n<html>\n<head><meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"><title>Check-ins (HTML version) | 4SQ Data Eggs beta</title></head>\n<body>\n<h2>Check-ins</h2>\n<table>\n";

	do {
		// DEBUG OPTION: &afterTimestamp=1420416000
		$checkins = json_decode(@file_get_contents("https://api.foursquare.com/v2/users/self/checkins?oauth_token=$token&sort=oldestfirst&limit=250&offset=$offset&v=20150327"), true);
		// echo str_replace("\n", "<br>", print_r($checkins, true));
		
		$items = $checkins["response"]["checkins"]["items"];
		foreach($items as $item) {
			echo "<tr style='border-top: 1px solid #cccccc;'><td>Check-in<td>".$item["id"]."</tr>\n";
			echo "<tr><td>Time<td>".date('Y-m-d H:i:s', $item["createdAt"])."</tr>\n";
			echo "<tr><td>Venue<td>".$item["venue"]["name"]."</tr>\n";
			echo "<tr><td>Location<td>".$item["venue"]["location"]["lat"].",".$item["venue"]["location"]["lng"]."</tr>\n";
			if(isset($item["shout"]))
				echo "<tr><td>Shout<td>".$item["shout"]."</tr>\n";
			if($item["photos"]["count"] > 0) {
				echo "<tr><td>Photos<td>";
				foreach($item["photos"]["items"] as $photo) {
					$imgurl = substr($photo["suffix"], 1);
					saveImage("$token/$imgurl", $photo["prefix"]."original".$photo["suffix"]);
					echo "<img src='$imgurl' border='0' height='200'/>";
				}
				echo "</tr>\n";
			}
		}

		//break;

		$offset += 250;
 		
	} while(count($items) == 250);
	
	echo "</table>\n<h5>Generated by 4SQ Data Eggs $version</h5>\n</body>\n</html>";
?>
